### PR TITLE
Remove Virtus

### PR DESCRIPTION
**Pull request by andyw8**

### CODE REVIEW

**Comment by mvz** [comment]
Hi @andyw8 any chance of this getting merged and released? This change would remove the dependency of [Reek](https://github.com/troessner/reek) on Virtus 1.x. This dependency bothers me because it's outdated (2.0.0 is out) and Virtus is discontinued.

**Comment by andyw8** [comment]
Hi @mvz, I don't use Reek or Code Climate on any current projects, but if you're able to test this to verify it then I'm happy to merge it and publish a new release.

**Comment by mvz** [comment]
Hi @andyw8 I've tested this with Reek and it works fine. The only issue is that all attributes are specified twice in the call to `attr_reader`, leading to warnings like so:

```
.../lib/cc_engine/issue.rb:72: warning: method redefined; discarding old check_name
```

**Comment by andyw8** [comment]
@mvz I fixed that issue and released v0.4.2.

**Comment by mvz** [comment]
Thanks, @andyw8!

**Pull request merged**
